### ISSUE TITLE
Closes when using up directory very quickly

### ISSUE THREAD

**Issue by VastOne** [IgnorantGuru/spacefm#509] opened 2015-04-26 20:36 UTC
If I am in a 3 deep directory and use the up level directory very quickly (3 clicks in 1 second or faster) SpaceFM closes with a Segmentation fault. 

Same three clicks slowly and it does not happen.. I can reproduce this at will

Perhaps not an issue at all, I will leave it to others to make that decision

**Comment by IgnorantGuru** [comment] 2015-04-26 20:57
Any segfault is an issue and should be reported.

What version/branch of SpaceFM are you using?  Sure this isn't caused by #504, fixed in next?

Are you displaying thumbnails or not?

What view style (Compact, Detailed, or Icon), and Large Icons or not?

Bookmarks shown or hidden has any effect?  Is one or more of the three dirs bookmarked?

I can't reproduce this in the book branch.  So a backtrace may be needed (please see BUILD DEBUG instructions in README).

**Comment by IgnorantGuru** [comment] 2015-04-26 21:06
Also, by "use the up level directory" I assume you mean you're clicking the toolbar Up item?

**Comment by VastOne** [comment] 2015-04-26 21:11
Using the latest book branch, built the day you created the latest branch so I may be 4 days behind?  I will build to the latest

It is not the same as #504 (to the best of my knowledge) I am not seeing any other crashes

I do use thumbnails but the directories I can reproduce this at will do not have any thumbs or videos in them so it seems to not be related

Detailed view and NO to large Icons. Toolbar is Menu style

Bookmarks shown always and and turning them off have nothing different. 

This also does not happen in every directory so you might want to try different ones.

I can reproduce it every time from this directory on my home ... 

/home/vastone/.gstreamer-0.10 

that directory has one file in it registry.x86_64.bin that has no special permissions

You your assumption is correct I am clicking the toolbar Up item in rapid succession

**Comment by VastOne** [comment] 2015-04-26 21:13
I will rebuild and start the DEBUG process and report back

**Comment by IgnorantGuru** [comment] 2015-04-26 21:16
Thanks.  Are you using GTK2 or GTK3 (see spacefm --version)

I can't reproduce this using the Up button or key combo Alt+Up.

A backtrace may be needed here.

**Comment by IgnorantGuru** [comment] 2015-04-26 21:18
In the BUILD DEBUG instructions, just change 'next' to 'book'.  in case this is related to recent bookmark changes, best to use that branch.

**Comment by VastOne** [comment] 2015-04-26 21:20
I am using GTK2 on a very simple Fluxbox setup...

I will use the book branch.. and start the retrace.  I will get it to you as soon as I can

**Comment by VastOne** [comment] 2015-04-27 01:08
I cannot recreate this in the latest next version.  I did run with gdb and without and where I could reproduce it every single time, I can no longer do it.  

This issue is solved.  

Sorry for the red herring IgnorantGuru, it was fun debugging something for a change... :dancers:

**Comment by VastOne** [comment] 2015-04-27 01:16
I also cannot reproduce this on the current next branch

**Comment by IgnorantGuru** [comment] 2015-04-27 01:35
No problem, I suspect it may have been one of the recent reports.  I'm assuming you also cleared the book branch.  Thanks for working on it - crashes are unacceptable to me so I'll always go the distance to get rid of any that are amply reported.  SpaceFM should never crash.  I used 0.9.4 for a year without a single one.  Of course that's because I fix any I encounter, but users can help do the same.

I'll give a nickel to anyone who finds one (*offer void everywhere).

**Closed by IgnorantGuru** 2015-04-27 01:35 UTC
Labels: bug, need info
