### ISSUE TITLE
Can no longer mount ssh and cifs in SpaceFM

### ISSUE THREAD

**Issue by kaqqao** [IgnorantGuru/spacefm#552] opened 2015-06-05 12:32 UTC
I have a pretty old installation of SpaceFm and udevil that I updated recently.
Now, when I type `ssh://user@host` in SpaceFm, I get:
```
nohup: ignoring input
fuse: bad mount point `/home/kaqqao/.cache/spacefm/ssh-<host>': No such file or directory
```
I now added `touch %a` to ssh protocol handler code and it now mounts it under `/home/kaqqao/.cache/spacefm/ssh-<host>' but it only allows me to see the remote user's home instead of the entire file system, like when I mount using udevil.

I tried simply disabling the ssh protocol handler, thinking SpaceFM will then fallback to udevil, but now I get asked for a password, the terminal closes immediately and nothing happens.

Somewhat similarly, if I type `//some_host/some_dir` in SpaceFM, it actually asks me to type the password (this is expected) but then errors with:

```
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
Running `udevil --mount //some_host/some_dir` works just fine, again mounts under /run/media/$USER.

Additionally, I've noticed that my /run/media directory disappeared recently. I had to recreate it for udevil to go back to normal, but it gets deleted on reboot! I'm using these on Arch, so maybe some Arch update did this.

Any clue what could be breaking SpaceFM?

**Comment by IgnorantGuru** [comment] 2015-06-07 14:48
> Now, when I type ssh://user@host in SpaceFm, I get:
> nohup: ignoring input
> fuse: bad mount point `/home/kaqqao/.cache/spacefm/ssh-<host>': No such file or directory

This sounds like something is having trouble parsing the hostname - you might want to include that here or include an obfuscated form of it which preserves any special characters.  Also, I notice the %a in the ssh handler command is not quoted, which it should be.  That might be the cause.

As for /run/media, that is no longer used by udisks2 (it violated FHS so they changed it to /media), and it will no longer be automatically created by udevil 0.4.4 and later.  So unless you create it at boot in a script, you should update udevil.conf to use /media or /media/$USER (udisks2 new default).

I can't explain the error from udevil, but if the media dir change doesn't correct it, the way to debug handlers is to run spacefm's first instance in a terminal, so you can see the output.  When you attempt to mount ssh in SpaceFM, check the terminal to see what commands it's running.  You can then run these same commands in a terminal to see where the handler may be going wrong.

The ssh handler has been around since 1.0.0, and the udevil mounting shouldn't have changed much, and there haven't been reports of ssh problems.  So I suggest focusing on the handler and the commands it's issuing or udevil's conf.

**Comment by kaqqao** [comment] 2015-06-07 17:18
I changed udevil.conf to mount under /media/$USER, that part seems OK now. Thanks a lot for the explanation!

SSH related, even though my host has no funky characters in its name, quoting the %a did cause some change. Still no success, though. This is what I get in the SpaceFM terminal:

```
Selected Protocol Handler 'ssh': MOUNT [ssh] mtab_fs=fuse.sshfs

TASK_COMMAND(0x1af6bd0)=fm_url_proto='ssh'; fm_url='ssh://root@training02'; fm_url_host='training02'; fm_url_port=''; fm_url_user='root'; fm_url_pass=''; fm_url_path=''; fm_mtab_fs=''; fm_mtab_url=''
[[ -n "$fm_url_user" ]] && fm_url_user="${fm_url_user}@"
[[ -z "$fm_url_port" ]] && fm_url_port=22
echo ">>> sshfs -p $fm_url_port $fm_url_user$fm_url_host:$fm_url_path /home/kaqqao/.cache/spacefm/ssh-training02"
echo
# Run sshfs through nohup to prevent disconnect on terminal close
sshtmp="$(mktemp --tmpdir spacefm-ssh-output-XXXXXXXX.tmp)" || exit 1
nohup sshfs -p $fm_url_port $fm_url_user$fm_url_host:$fm_url_path "/home/kaqqao/.cache/spacefm/ssh-training02" &> "$sshtmp"
err=$?
[[ -e "$sshtmp" ]] && cat "$sshtmp" ; rm -f "$sshtmp"
[[ $err -eq 0 ]]  # set error status

# Alternate Method - if enabled, disable nohup line above and
#                    uncheck Run In Terminal
# # Run sshfs in a terminal without SpaceFM task.  sshfs disconnects when the
# # terminal is closed
# spacefm -s run-task cmd --terminal "echo 'Connecting to $fm_url'; echo; sshfs -p $fm_url_port $fm_url_user$fm_url_host:$fm_url_path /home/kaqqao/.cache/spacefm/ssh-training02; if [ $? -ne 0 ]; then echo; echo '[ Finished ] Press Enter to close'; else echo; echo 'Press Enter to close (closing this window may unmount sshfs)'; fi; read" & sleep 1

[[ $? -eq 0 ]] || ( echo -n '[ Finished ]  Press Enter to close: ' ; read )

SPAWN=/usr/bin/lxterminal  -e  /bin/bash  /tmp/spacefm-kaqqao-0828860d.tmp/5199c67c-tmp.sh  run
    pid = 5799
child finished  pid=5799 exit_status=0
```
I could again try adding `touch %a` but that previously resulted only in mounting the home directory on the remote system, instead of the entire file system.

Can I somehow tell SpaceFM to just use udevil for SSH?

**Comment by IgnorantGuru** [comment] 2015-06-07 17:55
@Vladimir-csp Would you mind taking a look to see if you can reproduce a problem here?  Note that lxterminal is in use in case it's relevant.

You might also try the alternate method - in the commented section at the end of the ssh handler - to see if that makes a difference.  They use two different methods for resolving a problem where ssh tends to disconnect if the terminal window where it was mounted is closed.

> Can I somehow tell SpaceFM to just use udevil for SSH?

Yes, you can reorder the handler list so udevil's handler comes before ssh, or just disable the ssh handler by unchecking the 'Enable handler' box.  However I hope you'll also help us resolve the problem in the ssh handler.

I assume you're still receiving this error:

    fuse: bad mount point `/home/kaqqao/.cache/spacefm/ssh-<host>': No such file or directory

**Comment by IgnorantGuru** [comment] 2015-06-07 18:06
Also, the problem with the udevil handler may be that it closes the terminal when it's done, which may cause ssh to unmount.  You may need to copy that handler to create one just for ssh, and add a 'read' after the mount command, to keep the terminal open.  (There is an apparent bug in sshfs that disconnected on terminal close, and it's very fickle to control.  In our tests, the ssh handler avoided the problem.)

**Comment by Vladimir-csp** [comment] 2015-06-07 18:51
OK, you're trying to mount ```ssh://user@host``` - that should mount home dir - it is sshfs default behavior if no path specified.
Try mounting ```ssh://user@host/``` - this should get you fs root.
Tried with lxterminal, same thing.

If you still get error about mountpoint...
Does ~/.cache/spacefm exist?
Have you tried with clean SpaceFM config?
You mentioned ```touch %a```, it could interfere with mount process, as it may create simple file in place of mount point.

**Comment by kaqqao** [comment] 2015-06-07 18:53
Thanks for the tips! And of course I'd love to help troubleshoot this!
Regarding the error, it was still the same (<host> being "training02" in my specific case).

Right now, after messing with the handler script for a while (I set `$fm_url_path` to default to `/` if empty, and quoted `%a`), I somehow can not longer reproduce the issue... I'm still experimenting, and will also see what happens after a reboot, and will report.

**Comment by IgnorantGuru** [comment] 2015-06-08 14:22
To clarify a few general items:

* Normally substitution variables like %a are not quoted anywhere in SpaceFM.  Usually the contents are quoted before the %a is replaced.  That was the intention in handlers also, yet since the .cache dirs don't need quotes, it doesn't quote the dir internally before replacing %a.  If I now make it do so, it will break handlers that have %a quoted, so I'm disinclined to change it.  Overall it shouldn't matter,except in an unusual case where the mount dir contains special characters.

* The %a mount point dir is created before the handler is run, so touch should have no direct effect.

* The only config change that should affect a handler is the contents of the handler itself, and you can reset that with the Defaults button.  What you see in the terminal when SpaceFM mounts is the exact command as its issued.  That's it, except in this case you may be dealing with sshfs behavior when its terminal window closes, etc.

* When the handler run finishes, the %a dir is deleted if unmounted, or opened if mounted.

**Comment by IgnorantGuru** [comment] 2015-06-08 14:34
Actually, the problem here may be lxterminal.  There are several terminals which don't provide any way to make them start a new instance (they will instead open a new window in the current instance).  This means that the process SpaceFM starts to run a command in the terminal quits immediately, before the command in the terminal finishes.  This may mean that the %a dir is being deleted before sshfs has time to mount to it.  This may be why the problem is erratic and why touch (or any additional command) may affect it - it changes the speed and timing of the command.  So it may be a race condition.

The terminals that are known to be like this: lxterminal, urxvtc, konsole, gnome-terminal

I recommend testing with another terminal to determine if that's the cause.  With lxterminal, the problem may only appear if another lxterminal window is already open.  If the lxterminal instance started by SpaceFM for sshfs is the first lxterminal window open, the problem shouldn't occur.

If this is the problem, perhaps SpaceFM should only clean mount points that are a certain age (such as older than 60 seconds).  SpaceFM leaves temp files undeleted for these specific terminals and deletes them at the end of the command instead of at the end of the process.  But the %a dir is different as SpaceFM is always cleaning those mount points.

**Comment by IgnorantGuru** [comment] 2015-06-08 14:39
Also, the easiest way to test that problem is to put a 'read' line as the first line in your handler (which will cause it to pause in the terminal until you press Enter).  This pause will give you time to check if the SpaceFM task has ended (the lxterminal process it started has exited), and whether SpaceFM has deleted the %a dir already.

You could try this as the first few lines of the handler:
~~~~
ls %a
echo %a
sleep 1
ls %a
read
[the sshfs mount commands follow]
~~~~

**Comment by IgnorantGuru** [comment] 2015-06-08 16:32
I was able to reproduce some of the behavior with lxterminal and have pushed a fix for this to the next branch (see BUILD NEXT in README, or on Arch use AUR spacefm-git to test).

The fix causes SpaceFM to not delete the %a dir immediately after the process finishes, IF you are using lxterminal, urxvtc, konsole, or gnome-terminal.

However, due to the limitations of these terminals, the mount point dir probably won't be opened automatically (unless the handler does so explicitly).  (The process finishes before the mount is performed.)

Really I recommend using Roxterm or any of the other terminals, which should run single instances to avoid such problems.  That way the mount point will also open automatically after the mount command finishes, as it's designed to work.

**Comment by kaqqao** [comment] 2015-07-08 14:17
Sorry for long absence... Wasn't able to mess with that computer for a while.
I was finally able to experiment properly. You seem to be spot-on. Changing the terminal seems to help and the inconsistent behavior definitely stinks of a racing condition.
Thanks a bunch for the help and the fix! It's really incredible how fast you reacted!

**Comment by IgnorantGuru** [comment] 2015-07-12 14:01
Thanks for the followup.

**Closed by IgnorantGuru** 2015-07-12 14:01 UTC
Labels: fixed
