### ISSUE TITLE
Right-click activates bookmarks,  submenus etc. instead of opening properties menu for bookmark or menu etc..

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#529] opened 2015-05-14 11:24 UTC
Right-click activates bookmarks, submenus instead of opening properties menu for said item.  This makes it very difficult to access the desired design menu items for the submenu or bookmark.

This did not happen in previous builds (or I did not notice it in the last couple builds).

using:  1.0.1+201505140731.966~ubuntu14.04.1

**Comment by IgnorantGuru** [comment] 2015-05-14 15:45
This sounds like a duplicate of #521, which was caused by a malfunctioning GTK theme.  Test with [no theme in GTK2](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#invocation-gtkthemes), or the Adwaita theme in GTK3 for comparison.  If the problem persists with default themes, please add info below and this issue can be reopened.

**Comment by HerborenInVlammen** [comment] 2015-05-14 18:00
Hi:

The issue exists with Adwaita as well (all gtk3 themes actually).  If I
revert back to yesterday's daily build the problem does not exist. If I
install today's daily, the problem exists.

Note that I am using Mati75's unstable ppa for spacefm.

**Comment by IgnorantGuru** [comment] 2015-05-14 20:21
I can reproduce this in GTK 3.14.5 with my usual (and out of date) 3rd party theme.  However, I can't reproduce it using the Adwaita theme.

This is almost certainly a theme malfunction.  Also, iirc there were no recent changes to the click handler of Bookmarks.  That code hasn't changed in 6 days, and even then no changes to the click event handler were made.  So any change you see in that behavior between recent versions is likely incidental (eg some internal timing difference triggering a GTK3 bug).

If Adwaita doesn't work for you, this may indicate a problem with your mouse combined with GTK3, or a GTK3 bug (you should include your GTK3 version in this report).  The click on bookmarks is handled by a very routine handler that provides no control over the detailed behavior - GTK just passes the right-click event to the handler, so there are no refinements or precision control in SpaceFM's code.

**Comment by IgnorantGuru** [comment] 2015-05-14 20:36
Actually I do see some code affecting this in the menu itself - maybe I can adjust it.  Reopening #521.

**Comment by IgnorantGuru** [comment] 2015-05-14 20:49
As I noted in #521, this is probably fixed in the next branch.  Please add any further feedback on this to #521 so I'm not managing multiple issues - thanks.

**Closed by IgnorantGuru** 2015-05-14 20:49 UTC
Labels: duplicate
