### ISSUE TITLE
Cannot switch between running task windows

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#603] opened 2015-11-26 13:23 UTC
I regularly run two or more tasks within spacefm concurrently.  For example:  Update a SVN and compile something etc..  The seperate tasks complete just fine, but one cannot switch between the running task windows.  

Attempting to switch between tasks results in only the last task started window regardless of how the switch is invoked (mouse or keyboard, or via taskbar etc.).

**Comment by IgnorantGuru** [comment] 2015-11-27 10:18
Each task run dialog (or 'task window') is it's own X window (with SpaceFM as a parent), so normal window switching should apply.  This will vary with window manager.  Also, mind the [Stay On Top](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#tasks-dlg) and other settings that affect those dialogs.

On Openbox, if I click a task in the task manager, that dialog is shown.  If I click on another task in the list, the appropriate dialog is shown.  If I press Alt+Tab twice, the first task dialog appears (twice because it is beneath SpaceFM now in window ordering because clicking on the task list brought SpaceFM to the top).

So I'm not noticing anything unusual, and nothing should have changed here in recent releases.  You may want to note the output of spacefm --version, your GTK version (major and minor), and your WM with version.

**Comment by IgnorantGuru** [comment] 2015-11-27 10:27
Also, you might try opening SpaceFM and two task dialogs, then tile them on your screen so that they aren't on top of each other - each window in a separate area of the screen.  Then try your window switching to see how the window focus is changing.

**Comment by HerborenInVlammen** [comment] 2015-11-30 13:17
Thanks.  However, tiling and so on does not change the issue.  What occurs is that BOTH task windows go to the background and cannot be pulled to the foreground.  If I open a third task window it is in the foreground until I try to view any other task window, then all three are background windows that cannot be brought to the foreground.

**Comment by HerborenInVlammen** [comment] 2015-11-30 13:19
Thanks.  However, tiling and so on does not change the issue.  What occurs is that BOTH task windows go to the background and cannot be pulled to the foreground.  If I open a third task window it is in the foreground until I try to view any other task window, then all three are background windows that cannot be brought to the foreground.  

I can send a screen cast if it will help.

**Comment by IgnorantGuru** [comment] 2015-11-30 14:40
This certainly sounds like an xfwm related problem, as window focus seems to be broken.  No other reports like this, and xfce is a popular choice with SpaceFM users in general.

You might run xprop (run in terminal, then click mouse on window to be examined) on SpaceFM's main window, as well as a task window, and compare to apps of other windows.  If you find some property or other detail that you think is responsible, maybe it can be adjusted.

If you want details, SpaceFM creates the task dialog [here](https://github.com/IgnorantGuru/spacefm/blob/5ec58ecc9bf9e55c0d006e192b2ee3ad0f00d4a3/src/ptk/ptk-file-task.c#L824) and conditionally sets window properties [here](https://github.com/IgnorantGuru/spacefm/blob/5ec58ecc9bf9e55c0d006e192b2ee3ad0f00d4a3/src/ptk/ptk-file-task.c#L1124).  Nothing unusual there, except perhaps that the task dialog does NOT have the main window as a transient parent (NULL parent).  iirc this is done to allow greater flexibility re stay on top of other windows, etc. (it lets the dialog window act more independently of the main window).  So it should behave like any other X window.  I don't think this usage is incorrect but it could be revealing a problem in xfwm's handling of unparented dialogs.

Perhaps @OmegaPhil can try to reproduce this on xfwm?

I probably won't do anything more with this unless it's demonstrated there is a problem in SpaceFM's code or the window properties, but I'll leave this issue open to collect info.

**Comment by IgnorantGuru** [comment] 2015-11-30 15:09
This should probably be reported as a bug in xfwm not properly handling an unset WM_TRANSIENT_FOR.  It's similar to perhaps [this](https://mail.gnome.org/archives/wm-spec-list/2003-December/msg00036.html), though not exactly, since the task dialogs are not always modal (depending on options).

Long story short, if you click on a window with no transient for, your WM should bring it to front.  If it doesn't, that's almost certainly a bug.  Even if it defaults to transient for the window group, as in that discussion, it should still receive focus, not the main window, especially if not modal.

If you changed any of the default settings in  View|Task Manager|Popups, that would be good to note here as well.

**Comment by HerborenInVlammen** [comment] 2015-11-30 15:25
In truth. I do not need to do the tasks within spacefm... I mean how
many people are going to compile gmic, gimp, or other larger apps from a
spacefm session WHILE doing some other large task within spacefm?  Most
will do it from a terminal (and I can set the task to use a terminal
from within spacefm), however I am strange :)  It would be nice to know
though if I am the only one experiencing this.

BTW, it happens on the latest PCLinuxOS as well, which is Mandriva based
and runs a customized LXDE and an older stable version of spacefm (1.
something).  So, I still doubt it has to do with the wm on xubuntu, but
I know so little about such stuff.  Either way, it is no big deal.

Thank you for examining it :)

**Comment by IgnorantGuru** [comment] 2015-11-30 15:35
> BTW, it happens on the latest PCLinuxOS as well, which is Mandriva based and runs a customized LXDE and an older stable version of spacefm

For reference, the last change to this behavior in SpaceFM was probably #226 in 0.8.5 (3 years ago).  Even then, the transient-for was already unset, so that aspect wasn't changed.  Transient-for is deliberately unset because it's not desirable in this case to treat the window as a transient.

Most apps will set transient-for for dialogs, but SpaceFM allows greater-than-usual flexibility in how the task dialogs are presented and used, which is why you may not see it elsewhere.

I do suggest reporting it to xfwm, especially if reproduced.  However, LXDE uses Openbox.  I also use Openbox and have never seen this.  So if Openbox is doing it, it could be something else running that is interfering as well, though I wouldn't know what.  I would still suggest reporting it to xfwm as they may be more familiar with the general issues.

**Comment by OmegaPhil** [comment] 2015-11-30 18:17
Currently testing this on my programming desktop (using XFCE 4.12 here) - one SpaceFM window, started two task dialogs by requesting two large copy operations then pausing them. I'm able to Alt+TAB through the three windows and selecting any one window doesn't appear to affect any other SpaceFM window.

Currently task dialogs are configured:

Stay On Top: Off
Above Others: On
All Workspaces: On

Whats your configuration?

**Comment by HerborenInVlammen** [comment] 2015-12-06 19:57
Sorry to take so long to reply.  I have been on nights for the past 5
days... zzzz

Anyway, I have no problem with your example either.  So here is my
situation (also xfce 4.12 on Xubuntu trusty):

Under spacefm's Tools Menu I have created several entries using the NEW
> COMMAND design mode menu to run bash scripts and or commands sequences
that do things like download smplayer's latest svn, build and install
it; same ideas for gmic and gimp and several others etc.. 

These "commands are set as "tasks" in spacefm's Menu Item Properties -
Options tab (not run in a terminal).  If more than one of such tasks are
running you cannot properly cycle through the task windows.  This
happens in LXDE for me as well on PClinuxOS 64. 

Thanks for replying OmegaPhil.

**Comment by HerborenInVlammen** [comment] 2015-12-06 22:07
Oh, and to answer your question, my settings are: "stay on top" checked,
"above others" unchecked, and "all workspaces" unchecked.

When I set it your way, one indeed can cycle the windows, but no one
window is actually "on top" ... I.e., even though you can cycle through,
the window colors are background colors on all task windows... including
the foreground window.  So, possibly something is not quite right there?

Also, I guess what this really means is that if one has more than one
task window open, one cannot have BOTH (or all) of them set to "stay on
top" because then none will come to the foreground.  Try it.  I bet it
does it for you as well.

From a user point of view, neither scenario above works as expected IMO.

**Comment by IgnorantGuru** [comment] 2015-12-06 23:44
> Also, I guess what this really means is that if one has more than one task window open, one cannot have BOTH (or all) of them set to "stay on top" because then none will come to the foreground.  Try it.  I bet it does it for you as well.

Not reproducible for me on Openbox 3.5.2 with GTK 2.

Your report that custom task windows cycle differently than built-in task windows is very questionable.  Afaik they are created the same as far as the window manager is concerned, only low-level widget contents differ, which should not effect window switching at all.

Please provide the specific window manager versions you're encountering this on, what GTK version SpaceFM is using in each case, and what non-default settings you're using to reproduce the behavior, both in the task manager and the task options.  This report is vague on environmental details and no one has reproduced.  The well-tested behavior of SpaceFM in this area hasn't changed in years, and is documented in some detail.

**Comment by IgnorantGuru** [comment] 2015-12-07 01:48
Marking this as wontfix because this appears to be a (thus far non-reproducible) window manager malfunction.  Even if SpaceFM's particular usage is triggering the malfunction, it appears your window manager is out of spec or broken in how its handling the windows - not bringing a selected window to the foreground.

Feel free to add any more info below.  If it's demonstrated that this is a general problem among window managers, perhaps SpaceFM's usage can be adjusted for the broken window managers, but details would need to be provided.

Window manager behavior can vary, so adding a hack to accommodate some window managers could break it for others, and this code has been running well for years (lots of people use multiple task windows).  Any change in SpaceFM's behavior would need to be well tested generally with multiple window managers.

OmegaPhil, feel free to reopen this or investigate it further as you like.

**Closed by IgnorantGuru** 2015-12-07 01:48 UTC
Labels: need info

**Comment by OmegaPhil** [comment] 2016-02-22 21:38
Finally reached this again - I've redone my 'two large copy jobs' test with your Task Manager Popups configuration, and I can select the task windows, ALT+TAB between them etc.

Does that work for you? I'm thinking that the copy operations are valid non-terminal tests here, but if they aren't I guess I need to set up some test scripts.

**Comment by HerborenInVlammen** [comment] 2016-03-04 05:58
Thanks for the info.

I have it configured to a more or less acceptable way.... but it really
does have issues.  I can now alt-tab between them as well, but only if
they are minimized first.  Otherwise the window on the forefront just
stays on the forefront, but if you watch the task bar the focus moves
between the window buttons on the Xubuntu task bar (main panel) but this
does not change which window is displayed in the foreground.

I will keep fiddling with it.

From multiple file/folder selection being dropped on right-clicks to
whatever..., Spacefm has a "few" display anomalies that are blamed on
GTK, but I cannot repeat them on any other GTK app, nor have I
experienced them even randomly in any other app but Spacefm.  This may
be one of those.

**Comment by OmegaPhil** [comment] 2016-04-03 13:15
Reached this again - I've created two test Task commands to popup and not run in a terminal - they run the following, hopefully good enough to demonstrate a long-running task:

```bash -c 'while true; do sleep 1; done'```

Task dialogs in general configured as with yours, running the two test commands on a desktop with one normal SpaceFM window (amongst other program windows) - I can click between the dialogs and the main window, alt+tab between them, the window is graphically demonstrating its been selected etc etc.

Can you confirm that two instances of the above test command break for you?

If it does, we really need more people to come forward before any progress can be made with this (e.g. for me to get involved currently, it needs to break in my environment as it is now).
