### ISSUE TITLE
folder size option?

### ISSUE THREAD

**Issue by michalsykora** [IgnorantGuru/spacefm#487] opened 2015-03-22 00:40 UTC
Hi, I found out that from version 0.7.3 there is no possibility to show folder size.

I have an SSD which is fast and would like to have this option.

Maybe it will be good to have an option to show only size of selected folder, or calculate all shown folder sizes upon request for example by shortcut. This will be useful when transferring on external harddrives, especially for moving audio/video projects.

**Comment by IgnorantGuru** [comment] 2015-03-22 00:52
Closing as duplicate of #338  I agree it sounds useful.

**Closed by IgnorantGuru** 2015-03-22 00:52 UTC

**Comment by IgnorantGuru** [comment] 2015-03-22 00:53
Also no version of SpaceFM showed the recursive directory size - it's never been implemented.
