### ISSUE TITLE
Hotkeys do not work if keyboard layout different from EN is chosen

### ISSUE THREAD

**Issue by Temp24354** [IgnorantGuru/spacefm#520] opened 2015-05-10 09:34 UTC
I use two keyboard layouts: ru and en. I switch them using setxkbmap, and when RU is chosen, spacefm doesn't react on any hotkeys being pressed.

**Comment by IgnorantGuru** [comment] 2015-05-10 11:17
Closing as a duplicate of #57.  Note that you can still set custom keys and user them, just the default ones won't work.

**Closed by IgnorantGuru** 2015-05-10 11:17 UTC

**Comment by Temp24354** [comment] 2015-05-10 12:26
So, it is impossible to fix this bug in Spacefm's code, isn't it?

**Comment by IgnorantGuru** [comment] 2015-05-10 12:47
No, this may be fixed soon - maybe in the next release - subscribe to #57 for updates and you can help test any fix when it's ready.

**Comment by Temp24354** [comment] 2015-05-10 13:18
Thank you very much.
