### ISSUE TITLE
[1.0.5 GTK2] Black background while switching directories

### ISSUE THREAD

**Issue by morfikov** [IgnorantGuru/spacefm#627] opened 2016-03-08 17:57 UTC
After the update `spacefm:amd64 1.0.4-1 -> 1.0.5-1`, spacefm acts a little bit weird. The problem doesn't exists in the older version, just in the new. I was able to reproduce the weird behavior, so here are the steps.

- open a directory that has many files/folders in it, for example /etc/
- the horizontal scrollbar has to be visible, it only works when the scrollbar is present
- open another directory, it doesn't matter how you do it, you can use bookmarks, or just access some /etc/ subfolder. This can be done in the same tab, or in a new one.
- the more files in the new directory, the longer the back background will be shown.

It looks like this:

![screen](https://cloud.githubusercontent.com/assets/3797768/13610701/4fb28e02-e55f-11e5-9b8d-3c12118d85ea.png)

**Comment by IgnorantGuru** [comment] 2016-03-10 15:56
It's unlikely that any change between 1.0.4 and 1.0.5 would have affected this behavior.  If so it would likely be visual only, eg when GTK repaints the background.

As long as you see "Reading DIR..." in the status bar, as seen in your screenshot, this means that SpaceFM is reading the dir contents and opening some files to determine their MIME type.  In large directories this can take some time, so there is nothing shown until that completes.  Although a black background is unusual.

Also, the code which controls this directory loading has already been extensively rewritten.  In the alpha branch, which is still somewhat unstable, the directory contents are loaded faster and the MIME types are loaded in the background.  This code hasn't reached the release versions but is generally usable - you can read about it in #582.

**Comment by morfikov** [comment] 2016-03-10 16:50
I just installed and tested `spacefm-gtk3` in order to check whether the same behavior affects gtk3 version, and it looks like the `spacefm-gtk3` works just fine.

**Comment by cofi89** [comment] 2016-03-11 13:35
I'm seeing the similar behaviour since 1.0.5. Though only half of the first pane is black and it occurs only during startup/if there are no other spacefm windows open ( cannot reproduce with opening huge dirs as OP explained above ):  
![2016-03-11_scrot](https://cloud.githubusercontent.com/assets/6382833/13702817/a3423dfe-e791-11e5-93b8-61d4c110bb22.png)
   
Same with the alpha version, IIRC.  
```
[filip@debian][/tmp]$ spacefm --version
spacefm 1.0.5
GTK2 UDEV INOTIFY DESKTOP SNOTIFY 
[filip@debian][/tmp]$ apt-cache policy libgtk2.0-0
libgtk2.0-0:
  Installed: 2.24.25-3
  Candidate: 2.24.25-3
  Version table:
     2.24.25-3 0
        500 http://httpredir.debian.org/debian/ jessie/main i386 Packages
 *** 2.24.25-3 0
        100 /var/lib/dpkg/status
[filip@debian][/tmp]$ uname -a
Linux debian 4.1.8-ck2-bfq #1 PREEMPT Tue Sep 22 17:55:59 UTC 2015 i686 GNU/Linux
[filip@debian][/tmp]$ lsb_release -d
Description:	Debian GNU/Linux 8.3 (jessie)
```

**Comment by IgnorantGuru** [comment] 2016-03-11 14:19
@OmegaPhil added https://github.com/IgnorantGuru/spacefm/commit/88d08d8e73fcb123b71e078360bba4bd607a6fe2 in 1.0.5 to fix #578 which may be responsible for this.  Could also be https://github.com/IgnorantGuru/spacefm/commit/888a77357a97ffd7c49f5343503fe0c4229879b8 or https://github.com/IgnorantGuru/spacefm/commit/71f4d21d8594d4ce5bf52778ffc1c582173e88b3.

OmegaPhil, I'm not sure this is valid:
#if !GTK_CHECK_VERSION (3, 0, 0)
[code]
#endif

May need to be done like this?
#if GTK_CHECK_VERSION (3, 0, 0)
#else
[code]
#endif

Could you please check if your ifdef is working as expected there, and any other occurrences of that usage if incorrect.  If you need to make changes due to any of those commits, please commit to next - thanks.  This problem seems to be affecting GTK 2.

**Comment by Vladimir-csp** [comment] 2016-03-11 14:23
I have not seen this issue manifesting. 
```
spacefm 1.0.5
GTK2 UDEV INOTIFY DESKTOP SNOTIFY 
```
X.Org X Server 1.18.1, Intel video on Core i7-3540M with Compton compositor,

**Comment by morfikov** [comment] 2016-03-11 14:59
I can confirm that this affects only icon and compact view style.

**Comment by cofi89** [comment] 2016-03-11 17:10
@IgnorantGuru @OmegaPhil 
> @OmegaPhil added 88d08d8 in 1.0.5 to fix #578 which may be responsible for this. Could also be 888a773 or 71f4d21.  

Looks like it/they are the cause, over here atleast.
Reverting 88d08d8 and 888a773 fixes the issue ( I didn't build/test gtk3 ).    
On the side note, time taken from execution to icons being visible in both panes is now noticeably shorter, even without daemon running ( this athlon machine is slow enough for such, I guess normally unnoticable, performance gains to be visible ).

**Comment by IgnorantGuru** [comment] 2016-03-22 13:16
Pending @OmegaPhil reviewing this wrt #578, I have temporarily reverted 888a7735 in next and alpha (83332d0), which I think was the cause, although I was unable to reproduce the problem - may be theme dependent.  It was building as expected with the aforementioned ifdefs so they were not a problem as constructed.

**Comment by OmegaPhil** [comment] 2016-04-03 15:16
I can reproduce the 'black background on loading large directories with horizontal scrollbars with mulitple panes' problem - it looks like a duplicate/suspicious gdk_window_set_background call that was removed between v1.0.4 and v1.0.5, was actually needed here (the 'window' associated with the custom widget is already having its background set, so what is this other window?).

I don't have a problem with the ifdefs in general, they're just a logic construct? I'll look at the speed thing now.

**Comment by OmegaPhil** [comment] 2016-04-03 16:08
Right, I used my Debian Testing VM, set it to 10% of one core (so severely gimped), did 5 tests for the 2 panel '/usr/bin' test with v1.0.4 and v1.0.5 - with v1.0.4 the average time to start up and show the directories was 17.1 seconds, with v1.0.5 it was 18.5 seconds, so an 8% increase in time (this is without my latest fix).

I'm not convinced I'm seeing the same delay you are, thats just not different enough.

@IgnorantGuru: If the new code is 8% slower for no good reason but being more correct for style management, would you drop it? In answer to your email, exo_icon_view_realize is a realize function, so it runs once on creation of the widget (have confirmed this with printf).

**Comment by IgnorantGuru** [comment] 2016-04-03 16:23
@OmegaPhil  Okay sounds like my 83332d0 fix was incorrect, so feel free to revert that when you commit your changes for this.  I never could reproduce it.

If 8% slower, definitely drop it, unless there's some serious visual issue without it.

In general I recommend leaving the GTK2 code as-is rather than trying to improve it as you address GTK3 issues, or regressions become likely.  Ofc there are exceptions such as when you fixed some GTK2 issues, eg the bug on theme reload, etc.  Just in general try to tread carefully with GTK2 while addressing GTK3's ongoing development instability.

**Comment by OmegaPhil** [comment] 2016-04-03 16:29
I'm the wrong person to 'tread carefully' with this stuff - I have very little idea what I'm doing here.

OK, so this code was fixing the inability of the ExoIconView to react to theme changes - are you happy with this remaining broken then?

**Comment by IgnorantGuru** [comment] 2016-04-03 16:33
No, go ahead and fix that in GTK2 if possible - thanks.

**Comment by IgnorantGuru** [comment] 2016-04-03 16:37
Oh if you're saying the 8% slower code was fixing it's inability to react to style changes, I would say it's better to leave it broken.  Doesn't seem worth slowing down dir loading.  But you might see if the same speed issue is present in alpha, since that dir load code is more efficient in places, eg not updating as much.

**Comment by IgnorantGuru** [comment] 2016-04-03 17:07
You tread carefully just fine.  Fixing GTK issues often results in regression cycles.  The road to hell is paved with good intentions.

**Comment by IgnorantGuru** [comment] 2016-04-03 17:36
However testing alpha wrt to the speed change may be trickier due to background threads; perhaps not worth getting into it.  I would prefer unresponsive theme update over speed loss, so maybe better to leave it as prior, but at least leave your other code commented out with an explanation note for future reference?  Or if you wish to explore it further that's fine.  Note that some themes are remarkably slower than others.

In general, working on alpha dir load  I noticed some redundancy in the GTK refreshes, only some of which I addressed.  So it could be the speed change is primarily due to those, with your style set change having a cumulative effect.

**Comment by OmegaPhil** [comment] 2016-04-03 20:31
The earlier speed tests were not 100% useful as the host machine was using the ondemand scheduler. With the performance scheduler there are similar results:

1.0.4: 11.46 seconds
next with my changes: 12.72 seconds (+11%)
next with exo-icon-view.c reverted back to 1.0.4: 11.96 seconds (+4.4%)
next with background fix + revert of widget->style: 11.78 seconds (+2.8%)

So I think 1.0.5/next is still slower, but at some point the accuracy of the timing will be called into question. I have pushed this change now.

@cofi89: Does the latest next run any faster for you?

**Comment by cofi89** [comment] 2016-04-04 21:45
@OmegaPhil  
I don't have the time right now to properly test/measure, however from the "look and feel" and quick timing, I don't see any difference between latest Next and 1.0.5 with [reverted commits](https://github.com/IgnorantGuru/spacefm/issues/627#issuecomment-195459102). 
No black window "glitch", same performance ( ~2.2s cold & ~1.5s hot start ).  :+1:  
I'll let you know once I get to test cold "/usr/bin" loading, including 1.0.4 & clean 1.0.5.

**Comment by IgnorantGuru** [comment] 2016-04-05 09:39
Thanks - also merged your fix into alpha.  Closing this but feel free to comment/reopen as needed.

**Closed by IgnorantGuru** 2016-04-05 09:39 UTC
Labels: fixed
