### ISSUE TITLE
[GTK3] Dragging files to dir tree causes complete crash

### ISSUE THREAD

**Issue by LindyBalboa** [IgnorantGuru/spacefm#670] opened 2016-10-25 14:04 UTC
Running on Arch linux

Terminal output is 

```
fish: 'spacefm' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Teklad** [comment] 2017-02-16 00:27
I think I've figured this out.  Could you please try building the latest HEAD from https://github.com/Teklad/spacefm and let me know if the commit fixes your issue?

**Comment by LindyBalboa** [comment] 2017-02-16 08:41
Hi, I have since decided to use Dolphin. However, I just tested this but (now I realze) actually tested the main branch from here on IgnorantGuru and it seems the issue was resolved.

**Comment by syui** [comment] 2017-04-07 19:05
This problem is occurring again.

**Comment by IgnorantGuru** [comment] 2018-01-30 16:35
I am unable to reproduce this as of 78a5748d and I'm not aware of any recent changes that would have fixed it.  @Teklad's proposed fix in [7308bb6c](https://github.com/Teklad/spacefm-ng/commit/7308bb6ca02293332a4d229305a6212d45d25282) doesn't seem to change anything functionally, it just adds two variable declarations which are not used?  I don't see any other commit related to this.

I assume by "filetree" the OP meant that dragging is performed from the file list to the directory tree?

This report can use a backtrace from someone who encounters it - please see README|BUILD DEBUG.   Would also help to describe the style of the file list (eg Detailed, Icons, or Compact) and what is being dragged to where (eg a single or multiple files).  Please provide exact steps to reproduce.  A screenshot may be helpful to pinpoint any configuration dependency.  Also what version of GTK is being used (should be tested for any dependency on a particular GTK theme), and the output of: spacefm --version

**Comment by Teklad** [comment] 2018-01-30 17:18
If I remember correctly (been working too much to get any programming done for a while now), this issue is related to GTK3 in particular. _GdkDragContext appears to change between different versions of GTK3 which caused the crash.  I'm sure they added/removed some variables from that struct.... again, which is probably causing the issue to reoccur.

I'm not really sure what the best way to go about fixing it permanently would be.  Not relying on an ever-changing struct would probably yield better results if at all possible though, lol.

**Comment by IgnorantGuru** [comment] 2018-01-30 18:43
@Teklad Ah okay now I see what you did.  Yes it goes underneath the API with this. I have incorporated your fix, thanks!  3089c4d

I'm using an older version of GTK3, so any eyes and testing on this appreciated, eg maybe @BwackNinja or @OmegaPhil can take a look at how that struct is changing and whether this fix still applies.

**Comment by BwackNinja** [comment] 2018-01-30 21:09
We can probably use `gdk-drag-motion()` instead of embedding the private struct in here. I'll code up something later today.

https://developer.gnome.org/gdk3/stable/gdk3-Drag-and-Drop.html#gdk-drag-motion

**Comment by IgnorantGuru** [comment] 2018-01-30 22:04
@BwackNinja Ok thanks - that sounds more resilient.

**Comment by BwackNinja** [comment] 2018-02-11 02:41
Sorry for the delay. It took a while to wrap my head around how all of this was done. Created a pull request: https://github.com/IgnorantGuru/spacefm/pull/704

**Comment by IgnorantGuru** [comment] 2018-02-16 14:43
Thanks, merged into alpha.

**Closed by IgnorantGuru** 2018-02-16 14:43 UTC
Labels: fixed, pending

**Comment by Ruhrmolch** [comment] 2018-09-03 17:36
I still have that problem with Version 1.0.6
No terminal-output.

**Comment by BwackNinja** [comment] 2018-09-04 18:14
This fix is still in the alpha branch. You can build that and you should no longer experience this issue.

**Comment by warcayac** [comment] 2020-08-30 03:55
Recently I installed the version 1.0.6 on Pop! OS, same problem with drag and drop
