### ISSUE TITLE
Empty tab after unmounting a partition

### ISSUE THREAD

**Issue by morfikov** [IgnorantGuru/spacefm#568] opened 2015-08-19 18:56 UTC
I thought I was because of a system crash, but I'm able to reproduce this behavior.

Steps to reproduce:
- mount a partition
- open spacefm
- go to the partition's mount point, for example /media/partition/ -- there should be a content there
- close spacefm
- unmount the partition
- open spacefm -- the mount point it's empty
- mount the partition -- the mount point is still empty
-  try to open a new tab with the /media/partition/ (I was using the devices window), and the mount point is still empty, even though the partition is mounted.

When you manually type a sub folder in the address field, for instance /media/partition/folder/ , its content will be shown, but when you go to /media/partition/ (for example, using arrows) , it still will be empty.

There's only one option to solve this -- you have to close all tabs that point to the partition, and only then when you open the mount point in question, you will be able to get the directory/file listing.

**Comment by IgnorantGuru** [comment] 2015-08-19 19:43
I'm able to reproduce this using a cdrom, although in some cases View|Refresh worked.

SpaceFM is probably putting a udev watch on the unmounted mount point dir when it starts.  The mount detection probably needs to reset this watch once the point is mounted.  All new tabs will reuse the existing watch instead of duplicating or recreating it.

**Comment by IgnorantGuru** [comment] 2015-09-03 22:12
This is a tough one because there's so much going on in different threads and parts of the program.  Any solution I tried didn't work or caused problems in some cases.  I may revisit it.

As a workaround, if a single tab is involved, you should be able to refresh the tab (F5).  However, if you have multiple tabs open to the mount point dir, you'll need to close all but one before refresh will work.

Notes to self:  Even if every dir object is unrefed, it still won't finalize the object, thus refresh won't use a new dir object?  Also, refreshing a mount point dir in the process of being cleaned/removed prevents the tab from closing automatically due to timing issues.

**Comment by IgnorantGuru** [comment] 2015-09-07 00:16
What I have done is make it so that if a dir is mounted or unmounted, the tab closes, as if the directory was deleted (which in a sense it was).  This seems to work and avoids the problem I had refreshing the tabs.

Feedback welcome on this behavior.  To test, use the next branch per README.

**Comment by IgnorantGuru** [comment] 2015-09-07 00:30
No, I had to disable that change for now because it breaks auto-open of tab on automounts.  But you can try out the basic idea of the tabs closing by installing the 150264a commit like this:

    spacefm-installer --version=150264a

If it works otherwise I might address the automount interference and reinstate it.

**Comment by morfikov** [comment] 2015-09-07 10:12
I've just tested the version in question, and yes, it works as you described above.

I opened 3 tabs, closed spacefm, unmounted the partition, and then opened spacefm. Mounting the partition closes all the 3 tabs instantly, and there's no problem with directory/file listing when the mounting point is opened again. So I think the issue is fixed.

I have one question though. What about the path that points to a directory inside of the partition, for instance, when I open `/media/partition/folder1/folder2/`, close spacefm, unmount the partition and reopen spacefm, the tabs that point to `/media/partition/folder1/` or `/media/partition/folder1/folder2/` are changed to the `/home/$USER` directory. Should that happen, or should them be closed as well?

**Comment by IgnorantGuru** [comment] 2015-09-12 16:50
Thanks for testing.  This should now work in the 'bg' branch.  For alpha testing or comments please use #582.

> What about the path that points to a directory inside of the partition

Subdirs, once the mount point is unmounted, no longer exist, so that behavior is normal.  But you can see how the 'bg' version handles it.

**Closed by IgnorantGuru** 2015-09-12 16:50 UTC
Labels: bug
