### ISSUE TITLE
[Dialog] possible system-tray interaction?

### ISSUE THREAD

**Issue by paoloschi** [IgnorantGuru/spacefm#588] opened 2015-10-08 15:33 UTC
for me and people like me who __does not__ use a DE but only a window-manager, I think it would be very useful to create and interact with buttons or menus accessible from the system-tray from which control some bash script or desktop action and simultaneously receive notifications (..)

(I hope there is nothing wrong to mention here a unrelated outer project: I do it just to make sure I explain myself clearly because I speak english with difficulty..)
I mean a functionality such this one: <https://code.google.com/p/yad/wiki/NotificationIcon>

It may have added something similar to SpaceFM Dialog?
thank you

**Comment by IgnorantGuru** [comment] 2015-10-16 15:43
This is probably a duplicate of #156.  Review of this possibility has been delayed so long just because it requires research so is time consuming - keeps getting bumped down by other things.  In the meantime you can use yad or another dialog utility to integrate this functionality into SpaceFM Dialog scripts.

**Closed by IgnorantGuru** 2015-10-16 15:43 UTC
