### ISSUE TITLE
Unable to change virtual desktop with mousewheel in Openbox

### ISSUE THREAD

**Issue by jqrsd** [IgnorantGuru/spacefm#524] opened 2015-05-13 20:08 UTC
I have two vitrual desktops set in Openbox and since 1.0.1 it has become unable to change them with mousewheel (both using GTK 2 and 3 versions).

**Comment by IgnorantGuru** [comment] 2015-05-14 01:25
I can confirm that the scroll wheel in openbox doesn't work correctly when the SpaceFM DM is running.  I haven't yet looked at why that might be, but there weren't any recent changes that are likely to have affected this.  I just tested a pre-1.0.0 SpaceFM and the result was the same.

**Comment by jqrsd** [comment] 2015-05-14 13:35
Thanks for the prompt reply.
I've compared it with 0.9.4 version, where scrolling works fine.

**Comment by IgnorantGuru** [comment] 2015-05-23 15:57
This problem was introduced in 1.0.0 when BwackNinja enabled transparent desktop support in cd76d4d0 and 1807bd66.  There he re-enabled an old on_scroll handler from xfdesktop code that had been disabled by PCMan.  That code made some scroll-related fixes for icewm that apparently breaks Openbox.  I have [fixed this](https://github.com/IgnorantGuru/spacefm/commit/0997c3d3918cf02cbdab6a8c509b9fddfcc39ea3) by reverting the scroll handler to the default, so it doesn't call forward_event_to_rootwin().  But I'm not sure why @BwackNinja enabled it (and he has been out of communication lately), and I'm not sure what impact this will have on transparent desktop, so any testing of that by anyone is appreciated.

This problem should now be fixed in next, due for 1.0.2 release, pending feedback on transparent desktop impact.  Please see the BUILD NEXT instructions in README for testing.

**Comment by BwackNinja** [comment] 2015-05-23 16:45
Sorry if I seemed to disappear. I've still been around, but everything I'm mentioned in gets fixed before I get around to it. Rather than removing those lines (because then the handler does nothing and could just be removed again) a check should be put in place. The reason why it's there is so that scroll events get passed back to the root window, mostly for changing workspaces in Compiz in the transparent desktop case, because in that case, SpaceFM doesn't work as a desktop-type window.

The check should be the same as https://github.com/IgnorantGuru/spacefm/blob/master/src/desktop/desktop-window.c#L2472

**Comment by IgnorantGuru** [comment] 2015-05-23 17:40
@BwackNinja Good to hear all is well.  Thanks for the input - I'll make that conditional.

A few issues that could use your expertise when you have a moment:  #485 is a crash in GTK3 - seems 3.14 no longer agrees with some of the exo code.  @OmegaPhil has added this to his list, so you may want to sync with him on any work.  I'd say you're the most familiar there of all of us.  If it's a GTK3 bug I'd like a workaround, maybe conditional avoidance for now.

Also, #441 remains a mystery in case you have any thoughts on how to proceed, and #491 just so you're aware or can reproduce.

In the new work department, the icon chooser has been added in next for GTK2, but some of that exo code won't compile on GTK3, so it needs your conversion skills.  I had asked OmegaPhil but feel free to pick it up because you're familiar.  I ifdef'd out almost all the code in some of the exo files just so it builds with GTK3.  If you re-enable the icon chooser in settings.c:xset_text_dialog() for GTK3, the build errors will point the way.

Thanks and any level of participation is always appreciated.

**Closed** 2015-05-27 13:53 UTC
Labels: fixed, need info, pending
