### ISSUE TITLE
Columns need to be resized when switching to vertical (side-by-side) dual panel mode

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#668] opened 2016-10-07 03:19 UTC
When switching to a side-by-side panel mode, columns do not resize and it is hard to get info without scrolling etc.  They really should resize to fit the window just as Commander and the like do etc..

**Comment by IgnorantGuru** [comment] 2018-01-23 17:42
When switching panel modes, columns may need to be resized, but will be remembered for that panel combination, as described in [Panel Memory](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#gui-pan-mem).

As for autosizing, closing as a duplicate of #378

**Closed** 2018-01-23 17:42 UTC
Labels: duplicate
