### ISSUE TITLE
btrfs-clone support

### ISSUE THREAD

**Issue by antix-skidoo** [IgnorantGuru/spacefm#712] opened 2018-04-09 05:23 UTC
open since 2016 
https://github.com/Teklad/spacefm-ng/commit/e026a937e4befa9cc188957e3cae2f904439d75f

FYI, downstream is incorporating this change (Ubuntu, and now/soon Debian)
https://github.com/mati75/spacefm/blob/experimental/debian/patches/ubuntu.series

**Comment by IgnorantGuru** [comment] 2018-04-09 14:06
This is planned to be merged in soon.  Closing as a duplicate of #684.

**Closed as completed by IgnorantGuru** 2018-04-09 14:06 UTC
Labels: duplicate
