### ISSUE TITLE
[multiple screens issue]Menu doesn't diplayed on good screen

### ISSUE THREAD

**Issue by Obarun** [IgnorantGuru/spacefm#615] opened 2015-12-26 14:27 UTC
If i use multiple screen and i put spacefm on second screen (for eg.) when i try to open a menu (files, view, devices....) the menu is diplayed on the principal screen but not where spacefm is. So i have spacefm in a one screen and the menu in another, difficult to work with it lol.

**Comment by IgnorantGuru** [comment] 2015-12-26 14:56
So you're opening an initial SpaceFM window on a second screen and the right-click menus are appearing on the first screen.  You are not referring to the SpaceFM desktop manager, but a file manager window, and you have only one window open.  It's a very unusual problem.

Please include the output of: spacefm --version

Also, what window manager (eg openbox, xfwm, etc) are you using, and what version of it?

And what GTK version?  If you are not using the default GTK theme (Raleigh in GTK2 or Adwaita in GTK3, you may want to test to make sure a third party theme isn't causing breakage.

How are you starting SpaceFM (eg from a desktop or startmenu link, running from a terminal, etc.)?

You may also want to explain how you've setup the second screen, eg is a genuine X screen, an extension of the desktop to a second monitor, etc.

Overall, why are you seeing this problem and others aren't?  How can it be reproduced in general?  Thanks.

**Comment by Obarun** [comment] 2015-12-26 15:37
this trouble is permanent, i will answer you with the log output as soon as possible.

**Comment by IgnorantGuru** [comment] 2015-12-26 16:27
Overall this sounds more like a GTK bug or a window manager issue.  SpaceFM's code just tells GTK to show the menu, it doesn't handle the screens explicitly.  It could have something to do with the main window X properties combined with your particular window manager, etc.  But I've never seen a report like this regarding menus.

I doubt this can be fixed in SpaceFM as the problem likely is elsewhere, but getting version numbers and details on how your second screen is created will help narrow down where it's occurring.

**Comment by Obarun** [comment] 2016-01-04 04:12
@IG sorry for my late reply, i was very busy about pgp sign and other stuff on my system.
well,

this is the output of spacefm --version
> spacefm 1.0.2
GTK2 UDEV INOTIFY DESKTOP SNOTIFY 

i use openbox version 3.6.1
i use gtk2 2.24.29-1 and gtk3 3.18.6-1
test with different theme don't change anything

spacefm is started by xinit like this 
> spacefm --desktop -d &

no taskbar utilities, i use arandr with this command 
> xrandr --output VGA-0 --mode 1920x1080 --pos 1600x0 --rotate normal --output LVDS --mode 1600x900 --pos 0x0 --rotate normal

Well, i tried to make some change to make a race condition for debugging. First disabling spacefm --desktop -d on my xinit, log out and log in then launching spacefm by a terminal, the issue is not there anymore. 
So  i change again my xinit.rc and relaunch again spacefm --desktop but without daemonize it. log out log in again, the issue is not there too.
Well i change again my xinit.rc and relaunch spacefm --destktop -d. the issue is not there anymore.
it's absolutly incomprehensible but work.
So the issue is solved lol, sorry to make you waste your time. i don't like this trouble resolved by themself but....

**Comment by IgnorantGuru** [comment] 2016-01-04 11:28
Thanks for the followup.  I know what you mean about not liking it fixing itself, but X and GTK do sometimes develop mysterious glitches on a system level.  It's unusual to see with GTK2 and Openbox though.

As an alternative, you could try starting SpaceFM in ~/.config/openbox/autostart.sh instead of xinit, like this:

    (sleep 2 && spacefm --desktop) &

Perhaps that will affect it, and may give time for things to settle down.  Also, you don't need both --desktop and -d options, since --desktop automatically starts the daemon, though it shouldn't matter if you specify both.

Closing this but feel free to add any more info related to this.

**Closed by IgnorantGuru** 2016-01-04 11:28 UTC
Labels: need info, wontfix
