### ISSUE TITLE
spacefm won't start: Attempt to unlock mutex that was not locked error

### ISSUE THREAD

**Issue by riveravaldez** [IgnorantGuru/spacefm#468] opened 2014-09-30 13:38 UTC
Hi, I'm not sure (at all) if this is a SpaceFM error or came from another fount.
When I try to run SpaceFM it appears for an instant (like a flash) and then disappears.
I'm using Debian Testing:
```
$ uname -a
Linux user 3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux

$ spacefm
** (spacefm:2118): WARNING **: Ningún ajuste de root encontrado en /etc/spacefm/
Establecer un editor de root en Preferencias debería remover esta advertencia al inicio.
De otra manera commandos ejecutados como root pueden presentar un riesgo de seguridad.
spacefm: No such property from XGetWindowProperty() _NET_CURRENT_DESKTOP
Attempt to unlock mutex that was not locked
Abortado

$ spacefm --version
spacefm 0.9.4
GTK2 UDEV INOTIFY DESKTOP SNOTIFY
```
System is partially on Spanish. Roughly translation: *None root adjustment found on /etc/spacefm/ Establishing a root editor on Preferences should remove this warning at start. In other case, commands executed as root can present a security danger.*

Any hint?

Thanks a lot.

**Comment by IgnorantGuru** [comment] 2015-02-17 19:13
This "Attempt to unlock mutex that was not locked" error on SpaceFM startup is caused by upgrading from glib <= 2.40 to glib >= 2.41, while using GTK 2.24.24.  This was a bug in GTK2 which affected a lot of GTK2 apps.  eg you can see some discussion and links [here](https://bugs.launchpad.net/ubuntu/+source/gtk+2.0/+bug/1376530).

This problem was fixed upstream in GTK2 with version 2.24.25.  So building SpaceFM with glib >= 2.41 and GTK >= 2.24.25 should solve this problem.  No changes are required in SpaceFM.

In Debian, you only need to update these packages (which have no systemd dependency):
   libglib2.0-0 (2.40.0-3 => 2.42.1-1)
   libglib2.0-dev (2.40.0-3 => 2.42.1-1)
   gir1.2-gtk-2.0 (2.24.24-1 => 2.24.25-1)
   gtk2-engines-pixbuf (2.24.24-1 => 2.24.25-1)
   libgtk2.0-0 (2.24.24-1 => 2.24.25-1)
   libgtk2.0-0-dbg (2.24.24-1 => 2.24.25-1)
   libgtk2.0-bin (2.24.24-1 => 2.24.25-1)
   libgtk2.0-dev (2.24.24-1 => 2.24.25-1)

Thanks for the work providing workarounds for this, which may have been a temp fix for glib 2.41 with GTK 2.24.24.  However, I do ***not*** recommend using the gdk_threads_enter patches any longer, as it will probably interfere with SpaceFM's multithread support, and may cause other issues.

**Comment by BwackNinja** [comment] 2015-02-17 19:30
I've seen the problem with glib 2.41 and GTK3, and problems will still arise with older versions of GTK that SpaceFM does otherwise support. Also, I'd that using gdk_threads_enter is not just a workaround and is shown as the right way of doing things even in an old cairo tutorial here [1].

[1] http://cairographics.org/threaded_animation_with_cairo/

**Comment by IgnorantGuru** [comment] 2015-02-17 20:29
BwackNinja, okay thanks.  I didn't review the issue in detail.  Just off-hand, it just seems strange to use gdk_threads_enter/leave around the main gtk loop, but if that fix is working then maybe that is indeed the way to do it.  I did try to backtrace it but got nowhere - seems deep in GTK or glib.

**Comment by IgnorantGuru** [comment] 2015-02-17 20:43
Noting that BwackNinja has a patched version of SpaceFM on his [maintenance fork](https://github.com/BwackNinja/spacefm/commits/master) which includes a fix for this as well as some feature improvements.  You can grab the source via [this link](https://github.com/BwackNinja/spacefm/archive/master.tar.gz), and follow the normal build instructions in README.

**Comment by IgnorantGuru** [comment] 2015-03-02 17:01
BwackNinja fixed this in https://github.com/IgnorantGuru/spacefm/commit/f167b2831bc2556fc383cf30ae6ce4d117b67c04 (next branch) due in 0.9.5 release.

**Closed by IgnorantGuru** 2015-03-02 17:01 UTC
Labels: bug, fixed
