### ISSUE TITLE
Attempt to unlock mutex that was not locked

### ISSUE THREAD

**Issue by r004** [IgnorantGuru/spacefm#469] opened 2014-10-27 14:51 UTC
yesterday after a system-wide update I got this error:
```
Attempt to unlock mutex that was not locked
```
as I searched, I found out there is a problem with new Glib and older softwares.
I know that you don't maintain anymore. but please fix this issue in order to make spacefm usable again.
Cheers;
r004

**Comment by IgnorantGuru** [comment] 2015-02-17 17:39
This "Attempt to unlock mutex that was not locked" error on SpaceFM startup is caused by upgrading from glib <= 2.40 to glib >= 2.41, while using GTK 2.24.24.  This was a bug in GTK2 which affected a lot of GTK2 apps.  eg you can see some discussion and links [here](https://bugs.launchpad.net/ubuntu/+source/gtk+2.0/+bug/1376530).

This problem was fixed upstream in GTK2 with version 2.24.25.  So building SpaceFM with glib >= 2.41 and GTK >= 2.24.25 should solve this problem.  No changes are required in SpaceFM.

In Debian, you only need to update these packages (which have no systemd dependency):
   libglib2.0-0 (2.40.0-3 => 2.42.1-1)
   libglib2.0-dev (2.40.0-3 => 2.42.1-1)
   gir1.2-gtk-2.0 (2.24.24-1 => 2.24.25-1)
   gtk2-engines-pixbuf (2.24.24-1 => 2.24.25-1)
   libgtk2.0-0 (2.24.24-1 => 2.24.25-1)
   libgtk2.0-0-dbg (2.24.24-1 => 2.24.25-1)
   libgtk2.0-bin (2.24.24-1 => 2.24.25-1)
   libgtk2.0-dev (2.24.24-1 => 2.24.25-1)

Thanks to skalteis for providing his patch, which may have been a temp fix for glib 2.41 with GTK 2.24.24.  However, I do ***not*** recommend using that patch any longer, as it will probably interfere with SpaceFM's multithread support, and may cause other issues.

**Comment by IgnorantGuru** [comment] 2015-02-17 20:34
Closing this as a duplicate of #468.  Also, BwackNinja informs me there that he believes the patch to be a valid solution, which still corrects some issues with GTK3 and other versions, so I will defer to his experience on that.  He has included that patch in his maintenance fork.

**Closed** 2015-02-17 20:34 UTC
Labels: bug, duplicate
