### ISSUE TITLE
Suggestion : Add visual confirmation for cut action

### ISSUE THREAD

**Issue by CreeperLava** [IgnorantGuru/spacefm#625] opened 2016-02-28 15:10 UTC
I recently switched from Thunar to SpaceFM, as it is so much more powerful and configurable. One of the things I miss though is the visual confirmation you get in Thunar when cutting (Ctrl+X) one or more files : the icons of the selected files become a bit transparent. I haven't found this feature in SpaceFM. Would it be possible to add it ?
![screenshot_2016-02-28_16-10-56](https://cloud.githubusercontent.com/assets/12874678/13379967/de790994-de35-11e5-9fd1-3fdc9a9fe122.png)

**Comment by IgnorantGuru** [comment] 2016-03-10 16:02
Thanks - closing as a duplicate of #244

**Closed by IgnorantGuru** 2016-03-10 16:02 UTC
